### ISSUE TITLE
Hotfix - hiányzó dependenciák

### ISSUE THREAD

**Issue by 13alazs** [FodorAdam/Project-Protectors#20]
A maven implementációjával kibukott, hogy a menu (GameEngine.java) töri a build-et. Első ránézésre hiányzik a java.awt.color import, valamint nem működik megfelelően a javax.swing.* import. Ez magas prioritású feladat, mivel jelenleg törik legfrissebb release branch.
@FodorAdam mivel te írtad a kérdéses részt, így a legjobb lenne, ha te vennéd magadra, vagy legalábbis aki magára veszi beszélne veled.

**Comment by DoraZasz** [comment]
Mivel ez nagyrészt a mavenhez kapcsolódik, lehet hogy jobb lenne, ha én venném magamra

**Comment by 13alazs** [comment]
@DoraZasz támogatom, de ha a UI-jal kapcsolatban lenne kérdésed nyugodtan keresd @FodorAdam-ot

**Comment by FodorAdam** [comment]
Szerintem itt a konfliktusoknál ronthattam el valamit, ugyanis lemaradt 3 import véletlenül, majd nemsokára csinálok egy gyors bugfixet amikor készen leszek egy másik tickettel

**Comment by DoraZasz** [comment]
@FodorAdam Rendben, akkor azt megvárom, és utána megnézem hogy mennyire okés a maven ha már benne vannak az importok

**Comment by FodorAdam** [comment]
Elméletben kijavítottam az új branchben, de nézzetek rá

**Comment by 13alazs** [comment]
@FodorAdam csekkoltam és a build nálam már rendben lefut, de a pr-re írtam kommentet.
