### ISSUE TITLE
Tanári felhasználók hozzáadása GitHub-hoz

### ISSUE THREAD

**Issue by 13alazs** [FodorAdam/Project-Protectors#3]
"Ha valamilyen elterjedt és gyakran használt Git verziókezelő szolgáltatót használtok, pl. GitHub, GitLab, vagy Gitea, akkor adjátok hozzá @gerazo (GH (Linkek egy külső oldalra), GL (Linkek egy külső oldalra), GT (Linkek egy külső oldalra)) és @whisperity (GH (Linkek egy külső oldalra), GL (Linkek egy külső oldalra), GT (Linkek egy külső oldalra)) felhasználókat a legmagasabb hozzáférési szinten (Collaborator (GH), Administrator (GT), vagy Owner (GL))."

**Comment by whisperity** [comment]
A feladatkiírást **egyben** olvassuk el. Van egy

> Ha valamiért mégis egy zárolt/privát repót csináltok:

fejléce a bulletpointnak. Mivel ez a repó publikus, nem szükséges collaborator inviteot küldeni, látjuk így is. :slightly_smiling_face:

**Comment by 13alazs** [comment]
Hozzáadtam a tanári felhasználókat, hogy rálássanak a CI-ra.
