### ISSUE TITLE
Review minimum beállítás

### ISSUE THREAD

**Issue by 13alazs** [FodorAdam/Project-Protectors#7]
A repository adminisztrátor rendelkezik a jogosultsággal, hogy minimális számot állítson be a review-kra, melyek nélkül nem lehet merge-elni. A megbeszéltek alapján ezt a számot 2-re kell állítani.

**Comment by FodorAdam** [comment]
Szerintem megcsináltam, de nem vagyok benne teljesen biztos

**Comment by 13alazs** [comment]
Leteszteltem és úgy tűnik jól működik, így lezárom a ticket-et.
